title: Villa Windows
description: Specialists in Sash Windows and Timber Joinery in Auckland. Retrofit double-glazing, repair and maintenance.
baseurl: "/villawindows"
url: "https://villawindows.co.nz"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
permalink: pretty
